from pydantic import BaseModel, Field
from typing import List, Tuple


class ResearchQuestions(BaseModel):
    questions: List[str] = Field(default_factory=list,
                                 description='''List of questions which breakdown the main query into smaller parts to get a broader understanding of the topic the query is about. Should be a python list.
                                 ''')


class RelevantSnippet(BaseModel):
    reasoning: str = Field(description='''Reasoning behind the relevance of the snippet to the query.''')
    score: float = Field(description='''Score of the snippet based on its relevance to the query.
    1.0 means the snippet is relevant, 0.0 means it is not relevant. Be a very harsh critic and sparsely give 1.0 scores.''')


class Section(BaseModel):
    title: str = Field(description='''Title of the section.''')
    level_heading: int = Field(
        description='''Level of the heading in the document. For example, 1 for H1, 2 for H2, etc. upto 4''', lt=5,
        gt=0)
    questions: List[str] = Field(default_factory=list,
                                 description='''List of questions related to the section. These questions will be 
                                 used to generate the content of the section.''')
    content: str = Field(
        description="Should always be an empty string. The content of the section will be generated by another LLM.")
    sources: str = Field(
        description="Should always be an empty string. The content of the section will be generated by another LLM.")


class Skeleton(BaseModel):
    skeleton: List[Section] = Field(default_factory=list,
                                    description='''List of sections in the research report. Each section contains a title, level of heading, and content.
                                    You must include at least 3 sections in the report, an Introduction, a Body, and a Conclusion, but you should have atleast 6 sections in total.
                                    References should not be considered as a section.''')
